#!/bin/bash
# Bashrc SSH-tmux wrapper | Spencer Tipping
# Licensed under the terms of the MIT source code license

# Source this just after the PS1-check to enable auto-tmuxing of your SSH
# sessions. See https://github.com/spencertipping/bashrc-tmux for usage
# information.

if [[ -z "$TMUX" && -n "$SSH_CONNECTION" ]] && which tmux >& /dev/null; then
  # JGH Start
  # Little tweak to make things work with tmux 1.5, which does not have
  # the -F flag.
  # if ! tmux ls -F '#{session_name}' | grep "^ssh-$USER$" > /dev/null; then
  if ! tmux ls 2>&1 | cut -d ':' -f1 | grep "^ssh-$USER$" > /dev/null; then
  # JGH End
    echo "Starting new overall session"
    tmux -2 new-session -s ssh-$USER \; detach
  fi

  # Allocating a session ID.
  # There are two possibilities here. First, we could have a list of session
  # IDs that is densely packed; e.g. [0, 1, 2, 3, 4]. In this case, we want to
  # allocate 5.
  #
  # If, on the other hand, there is a gap, then it becomes unsafe to just use
  # #sessions as the new ID. So instead, we search through the list to see if
  # the difference between any pair is greater than one. (e.g. for [0, 1, 3, 5]
  # we would use 2)

  # JGH Start
  # Little tweak to make things work with tmux 1.5, which does not have
  # the -F flag.
  # sessions=($(tmux ls -F '#{session_name}' \
  #             | egrep "^ssh-$USER-[0-9]+$" \
  #             | sed "s/^ssh-$USER-//" \
  #             | sort -n))
  sessions=($(tmux ls | cut -d ':' -f1 \
              | egrep "^ssh-$USER-[0-9]+$" \
              | sed "s/^ssh-$USER-//" \
              | sort -n))
  # JGH End
  session_index=${#sessions[@]}

  for ((i = 1; i < ${#sessions[@]}; ++i)); do
    if (( ${sessions[$i]} - ${sessions[$((i - 1))]} > 1 )); then
      session_index=$((${sessions[$((i - 1))]} + 1))
      break
    fi
  done

  echo "Starting new throw-away session $session_index"
  exec tmux -2 new-session -s ssh-$USER-$session_index -t ssh-$USER
fi
